version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/_ignition/health-check" ]
      interval: 5s
      retries: 6
      timeout: 5s
    ports:
      - '${APP_PORT:-8000}:80'
    environment:
      APP_ENV: "local"
      APP_KEY: "base64:YqiENaRpmIOv6yCY2RcK0iqmIQvlXLj01AzpUgD54Tw="
      APP_DEBUG: "true"
    networks:
      - app

networks:
  app:
